publish = false
pre-release-commit-message = "chore: Release"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
consolidate-commits = true
allow-branch = ["main"]
pre-release-replacements = [
  {file="README.md", search="download.v.*.typos-checkstyle-v.*-x86_64", replace="download/{{tag_name}}/typos-checkstyle-{{tag_name}}-x86_64"},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/halkeye/typos-json-to-checkstyle/{{tag_name}}...HEAD", exactly=1},
]
